# Generated by Django 4.0.8 on 2023-03-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='input_class',
            field=models.CharField(choices=[('option-checkbox', 'option-checkbox'), ('option-btn', 'option-btn'), ('option-color', 'option-color'), ('option-rise-picker', 'option-rise-picker')], default='check-input', max_length=20),
        ),
    ]
