# Generated by Django 4.0.10 on 2023-08-08 23:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaitem',
            name='file',
            field=models.FileField(blank=True, upload_to=core.models.create_file_path),
        ),
    ]
