# Generated by Django 4.0.10 on 2024-01-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='frontend_autoplay',
            field=models.BooleanField(default=False),
        ),
    ]
