# Generated by Django 4.0.10 on 2024-02-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_metaitem_source2_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='use_sku_images',
            field=models.CharField(blank=True, help_text='If (use default images) is False, the images of product item that has the entered (sku) will be use even if the current product item has images', max_length=12),
        ),
    ]
