# Generated by Django 4.0.10 on 2023-08-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_metaitem_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='source2_url',
            field=models.URLField(blank=True, help_text='Set URL for icon image source e.g. PNG or JPG', max_length=255),
        ),
        migrations.AlterField(
            model_name='icon',
            name='source_url',
            field=models.URLField(blank=True, help_text='Set URL for icon SVG source', max_length=255),
        ),
    ]
