# Generated by Django 4.0.10 on 2023-08-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_icon_source2_url_alter_icon_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='use_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metaitem',
            name='source2_url',
            field=models.URLField(blank=True, help_text='You can set URL for icon image source e.g. PNG or JPG', max_length=255),
        ),
        migrations.AddField(
            model_name='metaitem',
            name='source_url',
            field=models.URLField(blank=True, help_text='You can set URL for icon SVG source', max_length=255),
        ),
        migrations.AddField(
            model_name='metaitem',
            name='use_source',
            field=models.BooleanField(default=False),
        ),
    ]
