# Generated by Django 4.0.8 on 2023-03-18 23:23

import core.models
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productitem_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('slug', models.SlugField(max_length=100)),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(upload_to=core.models.create_image_file_path)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_item_images_product_item', to='core.productitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
