# Generated by Django 4.0.10 on 2023-08-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_icon_use_source_metaitem_source2_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='use_source',
        ),
    ]
