# Generated by Django 4.0.10 on 2023-10-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_icon_use_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('title', models.CharField(max_length=40, unique=True)),
                ('summary', models.TextField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True, max_length=255)),
                ('frontend_link_text', models.CharField(default='Go', max_length=20)),
                ('display_order', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
