# Generated by Django 4.0.10 on 2023-03-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_thumbnail_productitemimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='thumbnail',
        ),
    ]
