# Generated by Django 4.0.10 on 2023-10-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_topbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbanner',
            name='summary',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='topbanner',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
