# Generated by Django 4.0.8 on 2023-03-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='is_item_option',
        ),
    ]
