# Generated by Django 4.0.10 on 2023-03-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_productattribute_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitemattribute',
            name='input_class',
            field=models.CharField(choices=[('option-select', 'option-select'), ('option-btn', 'option-btn'), ('option-color', 'option-color'), ('option-img', 'option-img')], default='option-select', max_length=20),
        ),
    ]
