# Generated by Django 4.0.8 on 2023-03-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_attribute_is_item_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='is_common_option',
            field=models.BooleanField(default=True, help_text='By selecting this option as True, means this attribute option will not show within the product item attribute suggestions for attribute_option field'),
        ),
    ]
