# Generated by Django 4.0.10 on 2023-03-29 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_productitemattribute_input_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitemattribute',
            name='input_class',
        ),
    ]
