# Generated by Django 4.0.8 on 2023-03-20 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_productattribute_is_common_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='is_common_option',
            new_name='is_common_attribute',
        ),
    ]
