# Generated by Django 4.0.10 on 2023-10-21 19:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_topbanner_url_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('rating', models.PositiveSmallIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='4')),
                ('is_accepted', models.BooleanField(default=False, help_text='By selecting this to be True, means this review is allowed by system to show in customer reviews')),
                ('po_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_po_profile', to='core.poprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_product', to='core.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
