# Generated by Django 4.0.10 on 2023-03-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_productitemattribute_input_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='input_class',
            field=models.CharField(choices=[('option-select', 'option-select'), ('option-btn', 'option-btn'), ('option-color', 'option-color'), ('option-img', 'option-img')], default='option-select', max_length=20),
        ),
    ]
