# Generated by Django 4.0.10 on 2023-03-29 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_productattribute_input_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='input_class',
        ),
    ]
