# Generated by Django 4.0.8 on 2023-03-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_is_common_option_productattribute_is_common_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
