# Generated by Django 4.0.8 on 2023-03-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='summary',
            field=models.TextField(blank=True, help_text='on frontend it is contained inside white colored block next to title promotion block', max_length=25),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(help_text='Can be use as coupon code, on frontend it is contained inside red colored block', max_length=12, unique=True),
        ),
    ]
