# Generated by Django 4.0.10 on 2023-03-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_productattribute_input_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='use_attribute_img',
            field=models.BooleanField(default=False),
        ),
    ]
