# Generated by Django 4.0.10 on 2023-04-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_use_attribute_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='use_attribute_img',
            new_name='use_item_attribute_color_shape',
        ),
        migrations.AddField(
            model_name='product',
            name='use_item_attribute_img',
            field=models.BooleanField(default=False),
        ),
    ]
