# Generated by Django 4.0.8 on 2023-03-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_promotion_summary_alter_promotion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='summary',
            field=models.TextField(blank=True, help_text='on frontend it is contained inside white colored block next to title promotion block', max_length=21),
        ),
    ]
