# Generated by Django 4.0.10 on 2023-05-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_productitem_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='unlimited_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotion',
            name='use_times',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
