# Generated by Django 4.0.10 on 2023-05-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_promotion_unlimited_use_promotion_use_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='use_times',
            new_name='max_use_times',
        ),
    ]
