# Generated by Django 4.0.10 on 2023-05-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_promotion_used_times_alter_promotion_max_use_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='limit_per_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
