# Generated by Django 4.0.10 on 2023-05-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_productitem_limit_per_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='limit_per_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
