# Generated by Django 4.0.10 on 2023-05-16 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_address_street_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Meta',
            },
        ),
        migrations.CreateModel(
            name='MetaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=56, unique=True)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_items_meta', to='core.meta')),
            ],
        ),
        migrations.AddConstraint(
            model_name='metaitem',
            constraint=models.UniqueConstraint(fields=('value', 'meta'), name='meta_item_unique_appversion'),
        ),
    ]
