# Generated by Django 4.0.10 on 2023-05-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_meta_metaitem_metaitem_meta_item_unique_appversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.RemoveConstraint(
            model_name='poitem',
            name='po_item_unique_appversion',
        ),
        migrations.RemoveField(
            model_name='poitem',
            name='purchase_order',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
