# Generated by Django 4.0.10 on 2023-05-18 20:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_purchaseorder_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='POPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('card_number', models.IntegerField(blank=True, null=True)),
                ('cardholder_name', models.CharField(blank=True, max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_payments_payment_method', to='core.paymentmethod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='POProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('role', models.CharField(default='client', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='POShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('cost_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3)),
                ('cost', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=8)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_shipping_address', to='core.address')),
            ],
        ),
        migrations.CreateModel(
            name='POStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('canceled', 'canceled')], default='Processing', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('po_code', models.CharField(max_length=50, verbose_name='PO code')),
                ('summary', models.TextField(blank=True, max_length=255)),
                ('po_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_po_payment', to='core.popayment')),
                ('po_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_po_profile', to='core.poprofile')),
                ('po_shipping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_po_shipping', to='core.poshipping')),
                ('po_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_po_status', to='core.postatus')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_promotion', to='core.promotion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('title', models.CharField(max_length=30, unique=True)),
                ('tax_percentage', models.DecimalField(decimal_places=0, default='0', help_text='Set tax percentage (0-100)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tax_fulfill', models.CharField(choices=[('after discount', 'After discount'), ('before discount', 'Before discount')], default='after discount', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='is_active',
            new_name='is_available',
        ),
        migrations.AddField(
            model_name='supplier',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales', 'Sales'), ('inventory', 'Inventory'), ('customer', 'Customer')], default='customer', max_length=30),
        ),
        migrations.DeleteModel(
            name='POItem',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_supplier', to='core.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_tax', to='core.tax'),
        ),
        migrations.AddField(
            model_name='poshipping',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_shipping_shipping_method', to='core.shippingmethod'),
        ),
        migrations.AddConstraint(
            model_name='poshipping',
            constraint=models.UniqueConstraint(fields=('shipping_method', 'address'), name='po_shipping_unique_appversion'),
        ),
    ]
