# Generated by Django 4.0.10 on 2023-05-18 20:24

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_paymentmethod_popayment_poprofile_poshipping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('price_per_unit_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'USD $')], default='USD', editable=False, max_length=3)),
                ('price_per_unit', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', help_text='You can set the value or automatically will set as product item current price', max_digits=8, validators=[djmoney.models.validators.MinMoneyValidator({'USD': 1}), djmoney.models.validators.MaxMoneyValidator({'USD': 5000})])),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_items_product_item', to='core.productitem')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_items_purchase_order', to='core.purchaseorder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='poitem',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'product_item'), name='po_item_unique_appversion'),
        ),
    ]
