# Generated by Django 4.0.10 on 2023-05-19 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_poitem_poitem_po_item_unique_appversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popayment',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='po_payments_payment_method', to='core.paymentmethod'),
            preserve_default=False,
        ),
    ]
