# Generated by Django 4.0.10 on 2023-05-20 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_shippingmethod_contact_name_shippingmethod_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_supplier', to='core.supplier'),
            preserve_default=False,
        ),
    ]
