# Generated by Django 4.0.10 on 2023-05-25 16:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_poshipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='country',
            name='iso_code',
            field=core.models.ISOCode(default='iq', max_length=2),
        ),
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(max_length=56, unique=True),
        ),
    ]
