# Generated by Django 4.0.10 on 2023-05-25 16:37

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_country_display_order_country_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=core.models.ISOCode(max_length=2, unique=True),
        ),
    ]
