# Generated by Django 4.0.10 on 2023-05-28 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_country_iso_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='is_active',
            new_name='is_available',
        ),
    ]
