# Generated by Django 4.0.10 on 2023-06-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_is_active_country_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
