# Generated by Django 4.0.10 on 2023-06-02 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_paymentmethod_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='popayment',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_payments_address', to='core.address'),
        ),
        migrations.AddField(
            model_name='popayment',
            name='use_shipping_address',
            field=models.BooleanField(default=True),
        ),
    ]
