# Generated by Django 4.0.10 on 2023-06-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_popayment_address_popayment_use_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_card',
            field=models.BooleanField(default=True),
        ),
    ]
