# Generated by Django 4.0.10 on 2023-06-03 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_paymentmethod_is_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods_icon', to='core.icon'),
        ),
    ]
