# Generated by Django 4.0.10 on 2023-06-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_paymentmethod_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='icon_color',
            field=models.CharField(default='fff', max_length=6),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='icon_color_select',
            field=models.CharField(default='0F1111', max_length=6),
        ),
    ]
