# Generated by Django 4.0.10 on 2023-06-04 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_paymentmethod_icon_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='icon_color_select',
        ),
    ]
