# Generated by Django 4.0.10 on 2023-06-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_paymentmethod_icon_color_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='tax',
        ),
    ]
