# Generated by Django 4.0.10 on 2023-06-19 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_countrytax_countrytax_country_tax_unique_appversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='country_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_tax', to='core.countrytax'),
        ),
    ]
