# Generated by Django 4.0.10 on 2023-06-19 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_purchaseorder_country_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='country_tax',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_tax', to='core.tax'),
        ),
        migrations.DeleteModel(
            name='CountryTax',
        ),
    ]
