---

# Caller workflow

# Define name of workflow.
name: Ecommerce CI

# Specify events.
on:
  push:
    branches: [main, staging, production]
  pull_request:


# Define workflow actions.
jobs:

  test:
    name: Run Tests
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ Ubuntu 20.04 ]
    environment: development
    steps:
      - uses: actions/checkout@v2
      - run: |
          cat << EOF > .env
          SECRET_KEY=${{secrets.SECRET_KEY}}
          DEBUG=${{secrets.DEBUG}}
          ALLOWED_HOSTS=${{secrets.ALLOWED_HOSTS}}
          CELERY_BROKER=${{secrets.CELERY_BROKER}}
          CELERY_BACKEND=${{secrets.CELERY_BACKEND}}
          SQL_IMAGE=${{secrets.SQL_IMAGE}}
          SQL_ENGINE=${{secrets.SQL_ENGINE}}
          SQL_HOST=${{secrets.SQL_HOST}}
          SQL_NAME=${{secrets.SQL_NAME}}
          SQL_USER=${{secrets.SQL_USER}}
          SQL_PASS=${{secrets.SQL_PASS}}
          SQL_PORT=${{secrets.SQL_PORT}}
          CACHE_IMAGE=${{secrets.CACHE_IMAGE}}
          CHOKIDAR_USEPOLLING=${{secrets.CHOKIDAR_USEPOLLING}}
          EOF
      - run: docker-compose build
      - run: docker-compose up db
      - run: docker-compose run --rm app bash -c "/usr/src/compose/start-django.sh"
      - run: docker-compose run --rm app bash -c "python manage.py test"

  lint:
    name: Lint
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ Ubuntu 20.04 ]
    environment: development
    steps:
      - uses: actions/checkout@v2
      - run: |
          cat << EOF > .env
          SECRET_KEY=${{secrets.SECRET_KEY}}
          DEBUG=${{secrets.DEBUG}}
          ALLOWED_HOSTS=${{secrets.ALLOWED_HOSTS}}
          CELERY_BROKER=${{secrets.CELERY_BROKER}}
          CELERY_BACKEND=${{secrets.CELERY_BACKEND}}
          SQL_IMAGE=${{secrets.SQL_IMAGE}}
          SQL_ENGINE=${{secrets.SQL_ENGINE}}
          SQL_HOST=${{secrets.SQL_HOST}}
          SQL_NAME=${{secrets.SQL_NAME}}
          SQL_USER=${{secrets.SQL_USER}}
          SQL_PASS=${{secrets.SQL_PASS}}
          SQL_PORT=${{secrets.SQL_PORT}}
          CACHE_IMAGE=${{secrets.CACHE_IMAGE}}
          CHOKIDAR_USEPOLLING=${{secrets.CHOKIDAR_USEPOLLING}}
          EOF
      - run: docker-compose build
      - run: docker-compose run --rm app bash -c "flake8"

  deploy_staging:
    name: Deploy to Staging
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    needs: [test, lint]
    if: github.ref == 'refs/heads/staging'

    steps:
      - uses: actions/checkout@v2
      - run: echo "Deploy to STAGING code here"

  deploy_production:
    name: Deploy to Production
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    needs: [test, lint]
    if: github.ref == 'refs/heads/production'

    steps:
      - uses: actions/checkout@v2
      - run: echo "Deploy to PRODUCTION code here"
